version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-volume:/app

volumes:
  postgres-volume:
    name: postgres
    driver: local
